App/library/abonent/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='home'),
    path('search-book', views.search, name='search-book'),
    path('read-tick', views.read_tick, name='read-tick'),
    path('add-tick', views.add_tick, name='add-tick'),
    path('issue-return', views.issue_return, name='issue-return'),
    path('report', views.report, name='report'),
    path('delete-tick/<int:pk>', views.delete_tick, name='delete-tick'),
    path('change-tick/<int:pk>', views.change_tick, name='change-tick'),
    path('issue-book', views.issue, name='issue-book'),
    path('return-book', views.return_book, name='return-book'),
    path('deptors', views.deptors, name='deptors'),
    path('delivery-books', views.del_books, name='del-books'),
]

App/library/library/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('abonent.urls')),
]

App/library/abonent/models.py
from datetime import timedelta, date

from django.db import models
from django.utils import timezone


class Publisher(models.Model):
    ID_publisher = models.IntegerField(primary_key=True)
    name_publisher = models.CharField(max_length=45)

    def __str__(self):
        return self.name_publisher

    class Meta:
        db_table = 'publisher'
        verbose_name = 'Publisher'


class Author(models.Model):
    ID_author = models.IntegerField(primary_key=True)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

    class Meta:
        db_table = 'author'
        verbose_name = 'Author'


class Book(models.Model):
    ISBN = models.CharField(max_length=20, primary_key=True)
    name = models.CharField(max_length=45)
    public_city = models.CharField(max_length=45)
    year = models.IntegerField()
    page_num = models.IntegerField()
    copies_num = models.IntegerField()
    publisher_ID_publisher = models.ForeignKey(Publisher, on_delete=models.CASCADE)
    authors = models.ManyToManyField(Author, related_name='books', null=True, blank=True)

    def __str__(self):
        return f"{', '.join(author.first_name + ' ' + author.last_name for author in self.authors.all())} - {self.name}"

    class Meta:
        db_table = 'book'
        verbose_name = 'Book'


class BookAuthor(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    author_ID_author = models.ForeignKey(Author, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.book}'

    class Meta:
        db_table = 'book_has_author'
        verbose_name = 'BooksAuthor'


class Reader(models.Model):
    read_ticket_num = models.AutoField(primary_key=True)
    PIB = models.CharField(max_length=100)
    home_adress = models.CharField(max_length=45)
    tel_work = models.CharField(max_length=10)
    tel_home = models.CharField(max_length=10, null=True, blank=True)
    birth_date = models.DateField()

    def __str__(self):
        return f'{self.read_ticket_num} - {self.PIB}'

    class Meta:
        db_table = 'readers'
        verbose_name = 'Reader'


class Copies(models.Model):
    inventory_num = models.IntegerField(primary_key=True)
    cost = models.DecimalField(max_digits=7, decimal_places=2)
    place = models.IntegerField()
    shelf = models.IntegerField()
    book_ISBN = models.ForeignKey(Book, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.book_ISBN)

    class Meta:
        db_table = 'copies'
        verbose_name = 'Copies'


class BooksDelivery(models.Model):
    readers_read_ticket_num = models.ForeignKey(Reader, on_delete=models.CASCADE)
    copies_inventory_num = models.ForeignKey(Copies, on_delete=models.CASCADE)
    date_issue = models.DateField(default=timezone.now, null=True, blank=True)
    date_return = models.DateField(null=True, blank=True)
    date_must_return = models.DateField(null=True, blank=True)

    class Meta:
        unique_together = ('readers_read_ticket_num', 'copies_inventory_num', 'date_issue')

    def save(self, *args, **kwargs):
        if not self.date_must_return:
            self.date_must_return = self.date_issue + timedelta(days=14)

        if self.pk is None:  # Якщо об'єкт щойно створено (видання книги)
            # Зменшуємо кількість екземплярів книги
            self.copies_inventory_num.book_ISBN.copies_num -= 1
        else:  # Якщо об'єкт вже існує (повернення книги)
            # Збільшуємо кількість екземплярів книги
            self.copies_inventory_num.book_ISBN.copies_num += 1
        self.copies_inventory_num.book_ISBN.save()
        super().save(*args, **kwargs)

    def get_date_issue_from_db(self):
        # Отримуємо дату видачі з БД
        return self.date_issue if self.pk else date.today()  # Якщо запис вже збережено у БД, повертаємо значення з БД, інакше повертаємо поточну дату

    def __str__(self):
        return str(self.copies_inventory_num)


class KnowledgeField(models.Model):
    unique_num = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=45)
    knowledge_field_unique_num = models.ForeignKey('self', on_delete=models.CASCADE)
    book = models.ManyToManyField(Book)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'knowledge_field'
        verbose_name = 'KnowledgeField'


class KnowledgeFieldHasBook(models.Model):
    knowledge_field_unique_num = models.ForeignKey(KnowledgeField, on_delete=models.CASCADE)
    book_ISBN = models.ForeignKey(Book, on_delete=models.CASCADE)

    class Meta:
        db_table = 'knowledge_field_has_book'
        verbose_name = 'KnowledgeFieldHasBook'
        unique_together = ('knowledge_field_unique_num', 'book_ISBN')

App/library/abonent/views.py
from django.db.models import Sum, Q
from django.db import IntegrityError
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse

from .forms import *
from .models import *

menu = [
    {'name': 'Головна', 'url_name': 'home'},
    {'name': 'Пошук книг', 'url_name': 'search-book'},
    {'name': 'Читацькі білети', 'url_name': 'read-tick'},
    {'name': 'Видача і повернення', 'url_name': 'issue-return'},
    {'name': 'Звіт', 'url_name': 'report'},
]


def index(request):
    context = {
        'title': 'Бібліотека',
        'menu': menu,
    }
    return render(request, 'abonent/index.html', context=context)


def search(request):
    query = request.GET.get('q')
    sort_by = request.GET.get('sort_by', 'name')  # сортувати за іменем, якщо параметр не вибраний
    sort_order = request.GET.get('sort_order', 'asc')  # за замовчуванням - сортування за зростанням

    if query:
        if query.isdigit():
            books = Book.objects.select_related('publisher_ID_publisher').prefetch_related('authors').filter(
                Q(year__icontains=query) |
                Q(page_num__icontains=query) |
                Q(copies__cost__icontains=query) |
                Q(copies_num__icontains=query)).distinct()  # прибрати дублікати
        else:
            books = Book.objects.select_related('publisher_ID_publisher').prefetch_related('authors').filter(
                Q(name__icontains=query) |
                Q(ISBN__icontains=query) |
                Q(authors__first_name__icontains=query) |
                Q(authors__last_name__icontains=query) |
                Q(public_city__icontains=query) |
                Q(publisher_ID_publisher__name_publisher__icontains=query)).distinct()  # прибрати дублікати
    else:
        books = Book.objects.select_related('publisher_ID_publisher').prefetch_related('authors').all()

    if sort_by:
        if sort_by == 'author':
            books = books.order_by('authors__first_name', 'authors__last_name')
        elif sort_by == 'city':
            books = books.order_by('public_city')
        elif sort_by == 'year':
            books = books.order_by('year')
        elif sort_by == 'pages':
            books = books.order_by('page_num')
        elif sort_by == 'cost':
            books = books.order_by('copies__cost')
        elif sort_by == 'copies':
            books = books.order_by('copies_num')
        else:
            books = books.order_by('name')

    if sort_order == 'desc':
        books = books.reverse()

    context = {
        'title': 'Пошук книг',
        'menu': menu,
        'books': books,
    }
    return render(request, 'abonent/search_books.html', context=context)


def read_tick(request):
    query = request.GET.get('q')
    sort_by = request.GET.get('sort_by', 'name')  # сортувати за іменем, якщо параметр не вибраний
    sort_order = request.GET.get('sort_order', 'asc')  # за замовчуванням - сортування за зростанням

    message = request.GET.get('message', '')

    if query:
        if query.isdigit():
            readers = Reader.objects.filter(
                Q(read_ticket_num__icontains=query) |
                Q(tel_work__icontains=query) |
                Q(tel_home__icontains=query)).distinct()  # прибрати дублікати
        else:
            readers = Reader.objects.filter(
                Q(PIB__icontains=query) |
                Q(home_adress__icontains=query) |
                Q(birth_date__icontains=query)).distinct()  # прибрати дублікати
    else:
        readers = Reader.objects.all()

    if sort_by:
        if sort_by == 'num':
            readers = readers.order_by('read_ticket_num')
        elif sort_by == 'date':
            readers = readers.order_by('birth_date')
        else:
            readers = readers.order_by('PIB')

    if sort_order == 'desc':
        readers = readers.reverse()

    context = {
        'title': 'Читацькі білети',
        'menu': menu,
        'readers': readers,
        'message': message,
    }
    return render(request, 'abonent/read_tick.html', context=context)


def add_tick(request):
    error = None
    if request.method == 'POST':
        form = ReaderForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('read-tick')
        else:
            error = form.errors.get('birth_date')

    form = ReaderForm()
    context = {
        'title': 'Додавання білету',
        'menu': menu,
        'form': form,
        'error': error
    }
    return render(request, 'abonent/add_read_tick.html', context=context)


def delete_tick(request, pk):
    tick = get_object_or_404(Reader, read_ticket_num=pk)

    issued_books = BooksDelivery.objects.filter(readers_read_ticket_num=tick, date_return=None)
    if issued_books.exists():
        message = 'Неможливо видалити читача, у якого є борг!'
        url = reverse('read-tick') + f'?message={message}'
        return redirect(url)
    else:
        tick.delete()
        message = 'Читач успішно видалений!'
        url = reverse('read-tick') + f'?message={message}'
        return redirect(url)


def change_tick(request, pk):
    error = None
    tick = get_object_or_404(Reader, read_ticket_num=pk)
    if request.method == 'POST':
        form = ReaderFormChange(request.POST, instance=tick)
        if form.is_valid():
            form.save()
            return redirect('read-tick')
    else:
        form = ReaderFormChange(instance=tick, initial={
            'PIB': tick.PIB,
            'home_adress': tick.home_adress,
            'tel_work': tick.tel_work,
            'tel_home': tick.tel_home,
            'birth_date': tick.birth_date,
        })

    context = {
        'form': form,
        'tick': tick,
        'tick_pk': pk,
        'error': error,
    }

    return render(request, 'abonent/change_tick.html', context)


def issue_return(request):
    form = BookDeliveryForm()
    message = request.GET.get('message', '')
    context = {
        'title': 'Видача і повернення',
        'menu': menu,
        'form': form,
        'message': message
    }
    return render(request, 'abonent/issue_return.html', context=context)


def issue(request):
    form = BookDeliveryForm()
    message = ''
    readers = Reader.objects.all()
    books = Book.objects.all()
    today = date.today()

    if request.method == 'POST':
        form = BookDeliveryForm(request.POST)
        if form.is_valid():
            selected_reader = form.cleaned_data['readers']
            selected_book = form.cleaned_data['book']
            date_issue = form.cleaned_data['date_issue']
            date_must_return = form.cleaned_data['date_must_return']
            date_return = form.cleaned_data['date_return']
            copies = Copies.objects.filter(book_ISBN=selected_book)

            if BooksDelivery.objects.filter(readers_read_ticket_num=selected_reader,
                                            date_return__isnull=True).count() >= 5:
                message = 'Неможливо видати книгу! У читача вже є 5 книг!'
                context = {
                    'title': 'Видача',
                    'menu': menu,
                    'readers': readers,
                    'books': books,
                    'today': today,
                    'form': form,
                    'message': message,
                }
                return render(request, 'abonent/issue.html', context=context)

            if copies.first().book_ISBN.copies_num == 0:
                message = 'Неможливо видати книгу! Кількість копій книги на складі дорівнює 0!'
                context = {
                    'title': 'Видача',
                    'menu': menu,
                    'readers': readers,
                    'books': books,
                    'today': today,
                    'form': form,
                    'message': message,
                }
                return render(request, 'abonent/issue.html', context=context)

            try:
                book_delivery = BooksDelivery(readers_read_ticket_num=selected_reader,
                                              copies_inventory_num=copies.first(),
                                              date_issue=date_issue, date_return=date_return,
                                              date_must_return=date_must_return)
                book_delivery.save()
                message = 'Книгу успішно видано!'
                url = reverse('issue-return') + f'?message={message}'
                return redirect(url)
            except IntegrityError as e:
                message = 'У читача вже є ця книга на руках!'
                context = {
                    'title': 'Видача',
                    'menu': menu,
                    'readers': readers,
                    'books': books,
                    'today': today,
                    'form': form,
                    'message': message,
                }
                return render(request, 'abonent/issue.html', context=context)

        else:
            form = BookDeliveryForm()

    context = {
        'title': 'Видача',
        'menu': menu,
        'readers': readers,
        'books': books,
        'today': today,
        'form': form,
        'message': message,
    }

    return render(request, 'abonent/issue.html', context=context)


def deptors(request):
    query = request.GET.get('q')
    sort_by = request.GET.get('sort_by', 'readers_read_ticket_num__read_ticket_num')
    sort_order = request.GET.get('sort_order', 'asc')  # за замовчуванням - сортування за зростанням

    if query:
        if query.isdigit():
            issued_books = BooksDelivery.objects.filter(
                Q(copies_inventory_num__book_ISBN__ISBN__icontains=query) |
                Q(copies_inventory_num__book_ISBN__name__icontains=query) |
                Q(readers_read_ticket_num__read_ticket_num__icontains=query)).distinct()  # убрать дубликаты
        else:

App/library/abonent/templates/abonent/add_read_tick.html
{% extends 'abonent/base.html' %}

{% block title %}
{{ title }}
{% endblock %}

{% block content %}
<h4 class="display-4" align="center">Інформація про нового читача</h4>
<form method="post">
    {% csrf_token %}
    <br>
    <div class="form-add">
        {% if error %}
        <div class="alert alert-danger" role="alert">
            {{ error }}
        </div>
        {% endif %}
        <br>
        {{ form.PIB }}
        <br>
        {{ form.home_adress }}
        <br>
        {{ form.tel_work }}
        <br>
        {{ form.tel_home }}
        <br>
        {{ form.birth_date }}
        <br>
        <button class="btn btn-primary" type="submit" style="padding-right: 20px; padding-left: 20px;">Додати
        </button>
        <a href="{% url 'read-tick' %}" class="btn btn-warning" style="margin-left: 3%;">Cancel</a>
    </div>
</form>
{% endblock %}

App/library/abonent/templates/abonent/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link type="text/css" href="{% static 'abonent/css/style.css' %}" rel="stylesheet"/>
    <link rel="shortcut icon" href="{% static 'abonent/images/favicon.ico' %}" type="image/x-icon"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
          integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    <!-- Select2 -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css" rel="stylesheet"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js"></script>
</head>
<body>
<div class="container border-bottom">
    <header class="d-flex justify-content-center py-3">
        <ul class="nav nav-pills">
            {% for m in menu %}
            <li class="me-3 py-2 link-body-emphasis text-decoration-none"><a href="{% url m.url_name %}"
                                                                             class="nav-link">{{ m.name }}</a></li>
            {% endfor %}
        </ul>
    </header>
</div>

<br><br>
<div class="container">
    {% block content %}

    {% endblock %}
</div>


</body>
</html>

App/library/abonent/templates/abonent/change_tick.html
{% extends 'abonent/base.html' %}

{% block title %}
Змінити білет
{% endblock %}

{% block content %}
<div>
<h4 class="display-4" align="center">Змінити інформацію про читача</h4>
<form method="post">
    {% csrf_token %}
    <br>
    <div class="form-add">
        {{ form.PIB }}
        <br>
        {{ form.home_adress }}
        <br>
        {{ form.tel_work }}
        <br>
        {{ form.tel_home }}
        <br>
        {{ form.birth_date }}
        <br>
        <button class="btn btn-primary" type="submit" style="padding-right: 20px; padding-left: 20px;">Змінити
        </button>
        <a href="{% url 'read-tick' %}" class="btn btn-warning" style="margin-left: 3%;">Cancel</a>
    </div>
</form>
    </div>
{% endblock %}

App/library/abonent/templates/abonent/del_books.html
{% extends 'abonent/base.html' %}

{% block title %}
{{ title }}
{% endblock %}

{% block content %}
<h4 class="display-4" align="center">Список виданих книг</h4>
<br>

<div class="table-responsive">
    <table class="table table-bordered">
        <thead class="table-secondary">
        <tr>
            <th>Книга</th>
            <th>ISBN</th>
            <th>Дата видачі</th>
            <th>Дата очікуваного повернення</th>
        </tr>
        </thead>

        <tbody>
        {% for book in issued_books %}
        <tr>
            <td style="width:23%">{{ book.copies_inventory_num.book_ISBN }}</td>
            <td style="width:16%">{{ book.copies_inventory_num.book_ISBN.ISBN }}</td>
            <td style="width:14%">{{ book.date_issue}}</td>
            <td style="width:15%">{{ book.date_must_return }}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>

</div>
{% endblock %}

App/library/abonent/templates/abonent/deptors.html
{% extends 'abonent/base.html' %}

{% block title %}
{{ title }}
{% endblock %}

{% block content %}
<h4 class="display-4" align="center">Список боржників</h4>
<label for="sort_by" style="padding-left: 59%;">Сортувати по:</label>

<div class="row">
    <div class="col-md-5">
        <form method="get" action="{% url 'deptors' %}">
            <div class="input-group mb-3">
                <button class="btn btn-outline-secondary" type="submit" id="button-addon1">🔍</button>
                <input type="text" class="form-control" placeholder="Соколовський Ігор" name="q">
            </div>
        </form>
    </div>
    <div class="col-md-7" style="padding-left: 17%;">
        <form method="get" action="{% url 'deptors' %}">
            <div class="input-group mb-3">
                <button class="btn btn-outline-secondary" type="submit">👉</button>
                <select name="sort_by" id="sort_by" class="form-select">
                    <option value="read_ticket">Читацький білет</option>
                    <option value="reader">Читач</option>
                    <option value="book">Книга</option>
                    <option value="date_issue">Дата видачі</option>
                    <option value="date_must_return">Дата очікуваного повернення</option>
                </select>
            </div>
            <label><input type="radio" name="sort_order" value="asc" checked> По зростанню</label>
            <label style="padding-left: 10%;"><input type="radio" name="sort_order" value="desc"> По спаданню</label>
        </form>
    </div>
</div>
<br>

<div class="table-responsive">
    <table class="table table-bordered">
        <thead class="table-secondary">
        <tr>
            <th>Номер читацького білету</th>
            <th>Читач</th>
            <th>Книга</th>
            <th>ISBN</th>
            <th>Дата видачі</th>
            <th>Дата очікуваного повернення</th>
        </tr>
        </thead>

        <tbody>
        {% for book in issued_books %}
        <tr>
            <td style="width:14%">{{ book.readers_read_ticket_num.read_ticket_num }}</td>
            <td style="width:18%">{{ book.readers_read_ticket_num.PIB }}</td>
            <td style="width:23%">{{ book.copies_inventory_num.book_ISBN }}</td>
            <td style="width:16%">{{ book.copies_inventory_num.book_ISBN.ISBN }}</td>
            <td style="width:14%">{{ book.date_issue}}</td>
            <td style="width:15%">{{ book.date_must_return }}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>

</div>
{% endblock %}

App/library/abonent/templates/abonent/index.html
{% extends 'abonent/base.html' %}
{% load static %}

{% block title %}
{{ title }}
{% endblock %}

{% block content %}

<h4 class="display-4" align="center">Абонентний відділ</h4>
<br>

<div class="table-responsive">

    <table class="table align-middle">

        <thead class="table-secondary">
        <tr>
            {% for m in menu %}
            {% if m.name != 'Головна' %}
            <th class="link-head"><a href="{% url m.url_name %}">{{ m.name }}</a></th>
            {% endif %}
            {% endfor %}
        </tr>
        </thead>

        <tbody>
        <tr>
            <td class="align-top">У формі ви можете знайти книгу, яка вам потрібна. А також сортувати іх за різними
                критеріям
            </td>
            <td class="align-top">На цій сторінці можна переглянути всіх читачів бібліотеки. Сортувати їх за різними
                критеріям. А також додати нового читача
            </td>
            <td class="align-top">Ця сторінка дозволяє видати книгу читачу. А також зафіксувати повернення книги
                читачем.
            </td>
            <td class="align-top">Тут можна передивитися звіт по бібліотеці. Наприклад: кількість читачів, кількість
                киг та інше.
            </td>
        </tr>
        <tr>
            <td class="align-top" align="center">
                <img src="{% static 'abonent/images/book.png' %}" width="65%" alt="Books">
            </td>
            <td class="align-top" align="center">
                <img src="{% static 'abonent/images/ticket.png' %}" width="70%" alt="Books">
            </td>
            <td class="align-top" align="center">
                <img src="{% static 'abonent/images/issue-return.png' %}" width="70%" alt="Books">
            </td>
            <td class="align-top" align="center">
                <img src="{% static 'abonent/images/report.png' %}" width="70%" alt="Books">
            </td>
        </tr>
        </tbody>
    </table>

</div>

{% endblock %}

App/library/abonent/templates/abonent/issue.html
{% extends 'abonent/base.html' %}

{% block title %}
{{ title }}
{% endblock %}

{% block content %}
<h4 class="display-4" align="center">Видача</h4>
<br>
{% if message %}
<div class="alert alert-danger" style="width: 70%; margin-left: auto; margin-right: auto;">{{ message }}</div>
{% endif %}
<div class="issue-book" style="width: 70%; margin-left: auto; margin-right: auto;">
    <form method="POST">
        {% csrf_token %}
        <p>Читач:</p>
        {{ form.readers }}
        <br><br>
        <p>Книга:</p>
        {{ form.book }}
        <br><br>
        <p>Дата видачі:</p>
        {{ form.date_issue }}
        <br>
        <p>Очікувана дата повернення:</p>
        {{ form.date_must_return}}
        <br>
        <button class="btn btn-primary" type="submit" style="padding-right: 20px; padding-left: 20px;">Видати
        </button>
        <a href="{% url 'issue-return' %}" class="btn btn-warning" style="margin-left: 3%;">Cancel</a>
    </form>
    {% if errors %}
    <ul>
        {% for error in errors %}
        <li>{{ error }}</li>
        {% endfor %}
    </ul>
    {% endif %}
</div>

<script>
<!--# Пошук у селект-->
$(document).ready(function() {
  $('.select2').select2();
});


<!--Автоматичне оновлення значення очікуваної дати повернення книги-->
var date_issue = document.getElementById("id_date_issue");
  var date_must_return = document.getElementById("id_date_must_return");

  date_issue.onchange = function() {
    var date = new Date(date_issue.value);
    date.setDate(date.getDate() + 14); // Установка даты, когда книгу нужно вернуть
    date_must_return.value = date.toISOString().slice(0,10); // Форматирование даты в формат ГГГГ-ММ-ДД
  };


</script>


{% endblock %}

App/library/abonent/templates/abonent/search_books.html
{% extends 'abonent/base.html' %}
{% load static %}

{% block title %}
{{ title }}
{% endblock %}

{% block content %}
<h4 class="display-4" align="center">Пошук книг</h4>
<label for="sort_by" style="padding-left: 59%;">Сортувати по:</label>

<div class="row">
    <div class="col-md-5">
        <form method="get" action="{% url 'search-book' %}">
            <div class="input-group mb-3">
                <button class="btn btn-outline-secondary" type="submit" id="button-addon1">🔍</button>
                <input type="text" class="form-control" placeholder="Тарас Шевченко" name="q">
            </div>
        </form>
    </div>
    <div class="col-md-7" style="padding-left: 17%;">
        <form method="get" action="{% url 'search-book' %}">
            <div class="input-group mb-3">
                <button class="btn btn-outline-secondary" type="submit">👉</button>
                <select name="sort_by" id="sort_by" class="form-select">
                    <option value="name">Назва</option>
                    <option value="author">Автор</option>
                    <option value="city">Місто</option>
                    <option value="year">Рік видання</option>
                    <option value="pages">Кількість сторінок</option>
                    <option value="cost">Вартість</option>
                    <option value="copies">Кількість екземплярів</option>
                </select>
            </div>
            <label><input type="radio" name="sort_order" value="asc" checked> По зростанню</label>
            <label style="padding-left: 10%;"><input type="radio" name="sort_order" value="desc"> По спаданню</label>
        </form>
    </div>
</div>


<br>
<div class="table-responsive">
    <table class="table table-bordered">
        <thead class="table-secondary">
        <tr>
            <th>ISBN</th>
            <th>Назва</th>
            <th>Автор</th>
            <th>Місто видання</th>
            <th>Видавництво</th>
            <th>Рік видання</th>
            <th>Кількість сторінок</th>
            <th>Вартість</th>
            <th>Кількість екземплярів</th>
        </tr>
        </thead>
        <tbody>
        {% for book in books %}
        <tr>
            <td style="width:15%">{{ book.ISBN }}</td>
            <td style="width:12%">{{ book.name }}</td>
            <td style="width:12%">
                {% for author in book.authors.all %}
                {{ author.first_name }} {{ author.last_name }}{% if not forloop.last %}, {% endif %}
                {% endfor %}
            </td>
            <td style="width:10%">{{ book.public_city }}</td>
            <td style="width:10%">{{ book.publisher_ID_publisher }}</td>
            <td style="width:12%">{{ book.year }}</td>
            <td style="width:10%">{{ book.page_num }}</td>
            <td style="width:10%">
                {% for copy in book.copies_set.all %}
                {{ copy.cost }}
                {% endfor %}
            </td>
            <td style="width:9%">{{ book.copies_num }}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}